### ISSUE TITLE
Return attributeList when using pid_to_eml_entity()

### ISSUE THREAD

**Issue by drkrynstrng** [NCEAS/arcticdatautils#118]
Currently, `pid_to_eml_entity()` does not return the attributeList for data objects. It would be useful to have an option to return the attributeList.

**Comment by jeanetteclark** [comment]
I don't think this is in the scope of the function. There are two use cases here:

- adding an object to a data package (workflow: `publish_object`, `set_attributes`, `pid_to_eml_entity` with attributeList as an argument)

- adding a physical section to an existing object (workflow: `pid_to_eml_physical`, insert `physical` into appropriate dataTable

@dmullen17 if you disagree feel free to reopen the issue, otherwise I'm closing
