### ISSUE TITLE
Make set_rights/set_rights_and_access check object class is SysMeta

### ISSUE THREAD

**Issue by amoeba** [NCEAS/arcticdatautils#38]
These functions trust the result but I think getSystemMetadata doesn't error out when it fails.

**Comment by amoeba** [comment]
This still needs to get looked into. Is it possible to to get cryptic errors when things don't work as expected?

**Comment by drkrynstrng** [comment]
If `getSystemMetadata` does not find the system metadata associated with a given PID on a given MN, then it returns a warning and NULL instead of an error. The NULL would then get passed on, which causes a somewhat cryptic error stating that the rightsHolder slot cannot be found, for example. `set_rights_and_access` will display the warning message `getSystemMetadata` gives that the system metadata could not be found for the given PID, though, which is informative, but these messages could be cleaned up. We can make the function stop if `getSystemMetadata` fails using
```
if (!inherits(sysmeta, "SystemMetadata")) {
      stop("Failed to get System Metadata.")
}
```
That seems robust to me, as long as the other error messages are informative.
